# readme.yml
extends: existence
message: "'%s' section is required"
level: error
scope: heading
ignorecase: false
tokens:
  - '^(## Introduction)'
  - '^(## Installation)'
  - '^(## Usage)'
  - '^(## Contributing)'