extends: occurrence

message: "Missing an 'Introduction' heading."
scope: heading
level: error
min: 1
token: "Introduction"

message: "Missing a 'Summary' heading."
scope: heading
level: error
min: 1
token: "Summary"

message: "Missing a 'Conclusion' heading."
scope: heading
level: error
min: 1
token: "Conclusion"