# This is a basic workflow that is automatically triggered at pushes to the app source code

name: AppInspect

on:
  push:
    paths:
      - 'packages/**'

jobs:
  build:
    uses: edro15/demo-splunkapp/.github/workflows/build.yml@master

  appinspect-cli:
    name: AppInspect CLI Validation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install splunk-appinspect

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged_app
      
      - name: Get artifact name
        id: app-name
        run: |
          app_package=$(ls -1 *gz | xargs basename)
          echo "package=${app_package}" >> $GITHUB_OUTPUT
      
      - name: Run AppInspect
        run: |
          splunk-appinspect inspect ${{ steps.app-name.outputs.package }} --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
