name: AppInspect

on:
  push:
    paths:
      - packages/**

jobs:
  appinspect-cli:
    name: AppInspect CLI Validation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install splunk-appinspect
      
      - name: Run AppInspect
        run: |
          splunk-appinspect inspect TA-sw-demo --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
        working-directory: ./packages
