# This is a basic workflow that is automatically triggered at tag

name: Release

on:
  push:
    # Push events to every tag including hierarchical tags like v1.0/beta
    tags:        
      - '*' 

permissions:
  contents: write
  packages: write

jobs:
  slim-validate:
    name: SLIM Validation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install splunk-packaging-toolkit

      - name: Slim Validate
        run: |
          slim validate packages/TA-sw-demo

  build:
    uses: edro15/demo-splunkapp/.github/workflows/build.yml@master

  release:
    name: Create Release
    needs: 
      - slim-validate
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: packaged_app
      
      - name: Create Release and Upload Asset
        run: |
          package_name=$(ls -1 *gz | xargs basename)
          gh release create ${{ github.ref_name }} $package_name
